import type { Place } from '@/domain/entities/Place';

export const mockPendingPlaces: Place[] = [
  {
    id: '1',
    name: 'Lanchonete do Zé',
    address: 'Rua Augusta, 450, Consolação',
    numero: '450',
    bairro: 'Consolação',
    cidade: 'São Paulo',
    estado: 'SP',
    lat: -23.5505,
    lng: -46.6333,
    establishmentType: 'Lanchonete',
    cuisineTypes: [],
    mealTypes: ['almoco', 'jantar'],
    foodTypes: ['salgados'],
    priceBucket: '15_25',
    description: 'Lanchonete tradicional com atendimento rápido',
    rating: 0,
    reviewsCount: 0,
    status: 'pending',
    createdBy: '@joao_sp',
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000),
    updatedAt: new Date(Date.now() - 2 * 60 * 60 * 1000),
  },
  {
    id: '2',
    name: 'Padaria Brasileira',
    address: 'Avenida Paulista, 1000, Bela Vista',
    numero: '1000',
    bairro: 'Bela Vista',
    cidade: 'São Paulo',
    estado: 'SP',
    lat: -23.5615,
    lng: -46.6561,
    establishmentType: 'Padaria',
    cuisineTypes: [],
    mealTypes: ['cafe'],
    foodTypes: ['salgados'],
    priceBucket: 'up_to_15',
    description: 'Padaria com pão fresco diariamente',
    rating: 0,
    reviewsCount: 0,
    status: 'pending',
    createdBy: '@maria_santos',
    createdAt: new Date(Date.now() - 4 * 60 * 60 * 1000),
    updatedAt: new Date(Date.now() - 4 * 60 * 60 * 1000),
  },
  {
    id: '3',
    name: 'Churrascaria do Sertão',
    address: 'Rua da Mooca, 200, Mooca',
    numero: '200',
    bairro: 'Mooca',
    cidade: 'São Paulo',
    estado: 'SP',
    lat: -23.5578,
    lng: -46.5895,
    establishmentType: 'Restaurante',
    cuisineTypes: ['brasileira'],
    mealTypes: ['almoco', 'jantar'],
    foodTypes: ['churrasco'],
    priceBucket: '40_70',
    description: 'Churrascaria com cortes nobres',
    rating: 0,
    reviewsCount: 0,
    status: 'pending',
    createdBy: '@ricardo_chef',
    createdAt: new Date(Date.now() - 6 * 60 * 60 * 1000),
    updatedAt: new Date(Date.now() - 6 * 60 * 60 * 1000),
  },
  {
    id: '4',
    name: 'Bar do Bião',
    address: 'Rua do Carmo, 85, Sé',
    numero: '85',
    bairro: 'Sé',
    cidade: 'São Paulo',
    estado: 'SP',
    lat: -23.5505,
    lng: -46.6361,
    establishmentType: 'Bar',
    cuisineTypes: [],
    mealTypes: ['jantar'],
    foodTypes: ['drinks'],
    priceBucket: '15_25',
    description: 'Bar tradicional com cervejas artesanais',
    rating: 0,
    reviewsCount: 0,
    status: 'pending',
    createdBy: '@carlos_noite',
    createdAt: new Date(Date.now() - 24 * 60 * 60 * 1000),
    updatedAt: new Date(Date.now() - 24 * 60 * 60 * 1000),
  },
  {
    id: '5',
    name: 'Pizzaria Luigi',
    address: 'Rua Aracy, 320, Pinheiros',
    numero: '320',
    bairro: 'Pinheiros',
    cidade: 'São Paulo',
    estado: 'SP',
    lat: -23.5625,
    lng: -46.6789,
    establishmentType: 'Pizzaria',
    cuisineTypes: ['italiana'],
    mealTypes: ['almoco', 'jantar'],
    foodTypes: ['pizza'],
    priceBucket: '25_40',
    description: 'Pizzaria com forno a lenha importado',
    rating: 0,
    reviewsCount: 0,
    status: 'pending',
    createdBy: '@luigi_napoli',
    createdAt: new Date(Date.now() - 8 * 60 * 60 * 1000),
    updatedAt: new Date(Date.now() - 8 * 60 * 60 * 1000),
  },
  {
    id: '6',
    name: 'Sushi Yama',
    address: 'Rua Bandeira, 180, Vila Mariana',
    numero: '180',
    bairro: 'Vila Mariana',
    cidade: 'São Paulo',
    estado: 'SP',
    lat: -23.6105,
    lng: -46.5895,
    establishmentType: 'Restaurante',
    cuisineTypes: ['japonesa'],
    mealTypes: ['almoco', 'jantar'],
    foodTypes: ['sushi'],
    priceBucket: '40_70',
    description: 'Sushi fresco com ingredientes importados',
    rating: 0,
    reviewsCount: 0,
    status: 'pending',
    createdBy: '@sushi_master',
    createdAt: new Date(Date.now() - 12 * 60 * 60 * 1000),
    updatedAt: new Date(Date.now() - 12 * 60 * 60 * 1000),
  },
  {
    id: '7',
    name: 'Café da Manhã',
    address: 'Travessa do Comércio, 42, Centro',
    numero: '42',
    bairro: 'Centro',
    cidade: 'São Paulo',
    estado: 'SP',
    lat: -23.5495,
    lng: -46.6371,
    establishmentType: 'Café',
    cuisineTypes: [],
    mealTypes: ['cafe'],
    foodTypes: ['cafe'],
    priceBucket: 'up_to_15',
    description: 'Café especializado com ambiente aconchegante',
    rating: 0,
    reviewsCount: 0,
    status: 'pending',
    createdBy: '@ana_cafe',
    createdAt: new Date(Date.now() - 14 * 60 * 60 * 1000),
    updatedAt: new Date(Date.now() - 14 * 60 * 60 * 1000),
  },
  {
    id: '8',
    name: 'Boteco do Zé',
    address: 'Avenida Brasil, 750, Santo Amaro',
    numero: '750',
    bairro: 'Santo Amaro',
    cidade: 'São Paulo',
    estado: 'SP',
    lat: -23.6215,
    lng: -46.7089,
    establishmentType: 'Boteco',
    cuisineTypes: [],
    mealTypes: ['jantar'],
    foodTypes: ['comida_caseira'],
    priceBucket: '15_25',
    description: 'Boteco tradicional com comida caseira',
    rating: 0,
    reviewsCount: 0,
    status: 'pending',
    createdBy: '@ze_boteco',
    createdAt: new Date(Date.now() - 24 * 60 * 60 * 1000),
    updatedAt: new Date(Date.now() - 24 * 60 * 60 * 1000),
  },
];
